version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps-api)"
