# permissions for end users to view deploymentstacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploymentstack-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resource-manager-controller
    app.kubernetes.io/part-of: resource-manager-controller
    app.kubernetes.io/managed-by: kustomize
  name: deploymentstack-viewer-role
rules:
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - deploymentstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - deploymentstacks/status
  verbs:
  - get
