---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - deploymentstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - deploymentstacks/finalizers
  verbs:
  - update
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - deploymentstacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - templatespecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - templatespecs/finalizers
  verbs:
  - update
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - templatespecs/status
  verbs:
  - get
  - patch
  - update
