# permissions for end users to edit templatespecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: templatespec-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: azure-controller-for-flux
    app.kubernetes.io/part-of: azure-controller-for-flux
    app.kubernetes.io/managed-by: kustomize
  name: templatespec-editor-role
rules:
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - templatespecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.contrib.fluxcd.io
  resources:
  - templatespecs/status
  verbs:
  - get
