apiVersion: azure.contrib.fluxcd.io/v1alpha1
kind: DeploymentStack
metadata:
  labels:
    app.kubernetes.io/name: deploymentstack
    app.kubernetes.io/instance: deploymentstack-sample
    app.kubernetes.io/part-of: azure-controller-for-flux
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: azure-controller-for-flux
  name: deploymentstack-sample
spec:
  stackName: deploymentstack
  deploymentScope: ResourceGroup
  location: uksouth
  templatePath: azuredeploy.json
  denySettingsMode: None
  sourceRef:
    kind: GitRepository
    name: deploymentstack
    namespace: flux-system
  interval: 1h
  retryInterval: 5m
